changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - wontfix
      - question
      - merge-conflict
  categories:
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
        - ci-failure
    - title: Performance
      labels:
        - performance
    - title: Documentation
      labels:
        - documentation
    - title: Refactoring & Maintenance
      labels:
        - refactor
        - chore
        - devops
        - ci
    - title: Other Changes
      labels:
        - "*"
